export const modelsList = [
  { 
    id: 1, 
    model: "gemini-2.5-flash", 
    provider: "gemini", 
    outputPrice: 2.5, 
    inputPrice: 0.30,
  },
  { 
    id: 2, 
    model: "gemini-3.5-flash", 
    provider: "gemini", 
    outputPrice: 9, 
    inputPrice: 1.5,
  },
  { 
    id: 3, 
    model: "gemini-3.5-flash-lite", 
    provider: "gemini", 
    outputPrice: 2.5, 
    inputPrice: 0.3,
  },
  { 
    id: 6, 
    model: "gemini-3-flash-preview", 
    provider: "gemini", 
    outputPrice: 3, 
    inputPrice: 0.5,
  },
  { 
    id: 7, 
    model: "gemini-3.1-flash-lite", 
    provider: "gemini", 
    outputPrice: 1.5, 
    inputPrice: 0.25,
  },
  {
    id: 8,
    model: "gemini-3.6-flash",
    provider: "gemini",
    outputPrice: 7.5,
    inputPrice: 1.5,
  },
  { 
    id: 9, 
    model: "qwen/qwen3.6-27b", 
    provider: "groq", 
    outputPrice: 3, 
    inputPrice: 0.6,
  },
  { 
    id: 10, 
    model: "llama-3.1-8b-instant", 
    provider: "groq", 
    outputPrice: 0.08, 
    inputPrice: 0.05,
  },
  { 
    id: 11, 
    model: "llama-3.3-70b-versatile", 
    provider: "groq", 
    outputPrice: 0.79, 
    inputPrice: 0.59,
  },
  { 
    id: 12, 
    model: "openai/gpt-oss-120b", 
    provider: "groq", 
    outputPrice: 0.6, 
    inputPrice: 0.15,
  },
  { 
    id: 13, 
    model: "openai/gpt-oss-20b", 
    provider: "groq", 
    outputPrice: 0.3, 
    inputPrice: 0.075,
  },
];